/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "lemmings.v:1.1-104.10" *)
module lemmings(clk, areset, bump_left, bump_right, ground, dig, walk_left, walk_right, aaah, digging);
  (* src = "lemmings.v:81.5-88.8" *)
  wire [4:0] _00_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _01_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _02_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _03_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _04_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _05_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _06_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _07_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _08_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _09_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _10_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _11_;
  (* src = "lemmings.v:25.5-78.8" *)
  wire [2:0] _12_;
  (* src = "lemmings.v:85.44-85.58" *)
  wire [4:0] _13_;
  (* src = "lemmings.v:101.20-101.38" *)
  wire _14_;
  (* src = "lemmings.v:101.43-101.62" *)
  wire _15_;
  (* src = "lemmings.v:102.23-102.40" *)
  wire _16_;
  (* src = "lemmings.v:102.45-102.63" *)
  wire _17_;
  (* src = "lemmings.v:48.31-48.47" *)
  wire _18_;
  (* src = "lemmings.v:48.21-48.47" *)
  wire _19_;
  (* src = "lemmings.v:84.18-84.63" *)
  wire _20_;
  (* src = "lemmings.v:85.25-85.40" *)
  wire _21_;
  wire _22_;
  (* src = "lemmings.v:85.24-85.66" *)
  wire [4:0] _23_;
  (* src = "lemmings.v:10.12-10.16" *)
  output aaah;
  wire aaah;
  (* src = "lemmings.v:3.11-3.17" *)
  input areset;
  wire areset;
  (* src = "lemmings.v:4.11-4.20" *)
  input bump_left;
  wire bump_left;
  (* src = "lemmings.v:5.11-5.21" *)
  input bump_right;
  wire bump_right;
  (* src = "lemmings.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "lemmings.v:22.15-22.22" *)
  reg [4:0] counter;
  (* src = "lemmings.v:7.11-7.14" *)
  input dig;
  wire dig;
  (* src = "lemmings.v:11.12-11.19" *)
  output digging;
  wire digging;
  (* src = "lemmings.v:6.11-6.17" *)
  input ground;
  wire ground;
  (* src = "lemmings.v:21.22-21.32" *)
  wire [2:0] next_state;
  (* src = "lemmings.v:21.15-21.20" *)
  reg [2:0] state;
  (* src = "lemmings.v:8.12-8.21" *)
  output walk_left;
  wire walk_left;
  (* src = "lemmings.v:9.12-9.22" *)
  output walk_right;
  wire walk_right;
  assign _13_ = counter + (* src = "lemmings.v:85.44-85.58" *) 1'h1;
  assign _18_ = counter >= (* src = "lemmings.v:56.31-56.47" *) 5'h14;
  assign _19_ = ground && (* src = "lemmings.v:56.21-56.47" *) _18_;
  assign _20_ = _14_ || (* src = "lemmings.v:84.18-84.63" *) _15_;
  assign _21_ = counter < (* src = "lemmings.v:85.25-85.40" *) 5'h15;
  assign aaah = _14_ | (* src = "lemmings.v:101.19-101.63" *) _15_;
  assign digging = _16_ | (* src = "lemmings.v:102.22-102.64" *) _17_;
  (* src = "lemmings.v:91.5-96.8" *)
  always @(posedge clk, posedge areset)
    if (areset) state <= 3'h0;
    else state <= next_state;
  (* src = "lemmings.v:81.5-88.8" *)
  always @(posedge clk, posedge areset)
    if (areset) counter <= 5'h00;
    else counter <= _00_;
  assign _09_ = dig ? (* full_case = 32'd1 *) (* src = "lemmings.v:40.26-40.29|lemmings.v:40.22-45.40" *) 3'h5 : _10_;
  assign _08_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:38.20-38.27|lemmings.v:38.16-45.40" *) _09_ : 3'h3;
  assign _07_ = bump_left ? (* full_case = 32'd1 *) (* src = "lemmings.v:32.26-32.35|lemmings.v:32.22-35.39" *) 3'h1 : 3'h0;
  assign _06_ = dig ? (* full_case = 32'd1 *) (* src = "lemmings.v:30.26-30.29|lemmings.v:30.22-35.39" *) 3'h4 : _07_;
  assign _05_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:28.21-28.28|lemmings.v:28.17-35.39" *) _06_ : 3'h2;
  function [2:0] _38_;
    input [2:0] a;
    input [20:0] b;
    input [6:0] s;
    (* full_case = 32'd1 *)
    (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *)
    (* parallel_case *)
    casez (s)
      7'b??????1:
        _38_ = b[2:0];
      7'b?????1?:
        _38_ = b[5:3];
      7'b????1??:
        _38_ = b[8:6];
      7'b???1???:
        _38_ = b[11:9];
      7'b??1????:
        _38_ = b[14:12];
      7'b?1?????:
        _38_ = b[17:15];
      7'b1??????:
        _38_ = b[20:18];
      default:
        _38_ = a;
    endcase
  endfunction
  assign next_state = _38_(3'h0, { _05_, _08_, _11_, _01_, _03_, _04_, 3'h6 }, { walk_left, walk_right, _14_, _15_, _16_, _17_, _22_ });
  assign _22_ = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h6;
  assign _17_ = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h5;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h4;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h3;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h2;
  assign walk_right = state == (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) 3'h1;
  assign walk_left = ! (* full_case = 32'd1 *) (* src = "lemmings.v:0.0-0.0|lemmings.v:26.9-77.16" *) state;
  assign _00_ = _20_ ? (* full_case = 32'd1 *) (* src = "lemmings.v:84.18-84.63|lemmings.v:84.14-87.29" *) _23_ : 5'h00;
  assign _04_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:70.21-70.27|lemmings.v:70.17-73.45" *) 3'h5 : 3'h3;
  assign _03_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:64.21-64.27|lemmings.v:64.17-67.44" *) 3'h4 : 3'h2;
  assign _02_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:58.26-58.32|lemmings.v:58.22-61.45" *) 3'h1 : 3'h3;
  assign _01_ = _19_ ? (* full_case = 32'd1 *) (* src = "lemmings.v:56.21-56.47|lemmings.v:56.17-61.45" *) 3'h6 : _02_;
  assign _12_ = ground ? (* full_case = 32'd1 *) (* src = "lemmings.v:50.26-50.32|lemmings.v:50.22-53.44" *) 3'h0 : 3'h2;
  assign _11_ = _19_ ? (* full_case = 32'd1 *) (* src = "lemmings.v:48.21-48.47|lemmings.v:48.17-53.44" *) 3'h6 : _12_;
  assign _10_ = bump_right ? (* full_case = 32'd1 *) (* src = "lemmings.v:42.26-42.36|lemmings.v:42.22-45.40" *) 3'h0 : 3'h1;
  assign _23_ = _21_ ? (* src = "lemmings.v:85.24-85.66" *) _13_ : 5'h1f;
endmodule
